bitstat:
  # port to listen for commands from bitstatctl
  port: 10000
  # defines how often will be data_providers requested for new data (in seconds)
  tick: 1
  # path to vestat file for counting cpubusy
  vestat_path: /proc/vz/vestat
  # path to user bean resources
  resources_path: /proc/bc/resources
  # fields to list in vzlist
  vzlist_fields:
    - diskspace
    - diskinodes
  # id to identify this instance of bitstat
  node_id: 1
  # timeout after which will 'SIGKILL' be sent when stopping bitstat
  force_kill_waittime: 30
  filesystem_prefix: vz/private/
  enabled_data_providers:
    - zfs_diskspace
    - cpubusy
    - physpages

bitsuper:
  url: https://admin:admin@localhost:30000
  # verifies server cert when executing rest client call
  verify_crt: false
  # absolute path to CA crt
  ca_crt_path: /etc/ssl/relbit/ca.crt

devel:
  # sets $DEBUG flag
  debug: false

logging:
  # 'supervisor', 'stderr' or path to logfile
  target: stderr
  # level from which log - debug, warn, info, error, fatal
  level: debug